package com.cary.sanke.dao;

import com.cary.sanke.pojo.Productimage;

public interface ProductimageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int insert(Productimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int insertSelective(Productimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    Productimage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Productimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Productimage record);
}