package com.cary.sanke.dao;

import com.cary.sanke.pojo.Propertyvalue;

public interface PropertyvalueDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int insert(Propertyvalue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int insertSelective(Propertyvalue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    Propertyvalue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Propertyvalue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Propertyvalue record);
}